package com.hzq.shop.domain;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.county
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail_addr
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String detailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.receipt_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String receiptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.receipt_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String receiptTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addr_id
     *
     * @return the value of address.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addr_id
     *
     * @param addrId the value for address.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.cust_detail_id
     *
     * @return the value of address.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustDetailId() {
        return custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.cust_detail_id
     *
     * @param custDetailId the value for address.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustDetailId(Long custDetailId) {
        this.custDetailId = custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.county
     *
     * @return the value of address.county
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.county
     *
     * @param county the value for address.county
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail_addr
     *
     * @return the value of address.detail_addr
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getDetailAddr() {
        return detailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail_addr
     *
     * @param detailAddr the value for address.detail_addr
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setDetailAddr(String detailAddr) {
        this.detailAddr = detailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.receipt_name
     *
     * @return the value of address.receipt_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getReceiptName() {
        return receiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.receipt_name
     *
     * @param receiptName the value for address.receipt_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setReceiptName(String receiptName) {
        this.receiptName = receiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.receipt_tel
     *
     * @return the value of address.receipt_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getReceiptTel() {
        return receiptTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.receipt_tel
     *
     * @param receiptTel the value for address.receipt_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setReceiptTel(String receiptTel) {
        this.receiptTel = receiptTel;
    }
}