package com.hzq.shop.domain;

import java.util.Date;

public class Cust {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_detail_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private Long custDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_sstatus
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custSstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_pass_msg
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custPassMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_pass_msg_answer
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custPassMsgAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_email
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_true_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custTrueName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_identity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custIdentity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_tel
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_sex
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.addr_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private Long addrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.post_code
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.vip_lever
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private Integer vipLever;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.login_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.login_pass
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String loginPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_role
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String custRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.register_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private Date registerDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.last_login_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private Date lastLoginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.is_activity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	private String isActivity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_detail_id
	 * @return  the value of cust.cust_detail_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public Long getCustDetailId() {
		return custDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_detail_id
	 * @param custDetailId  the value for cust.cust_detail_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustDetailId(Long custDetailId) {
		this.custDetailId = custDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_sstatus
	 * @return  the value of cust.cust_sstatus
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustSstatus() {
		return custSstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_sstatus
	 * @param custSstatus  the value for cust.cust_sstatus
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustSstatus(String custSstatus) {
		this.custSstatus = custSstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_pass_msg
	 * @return  the value of cust.cust_pass_msg
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustPassMsg() {
		return custPassMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_pass_msg
	 * @param custPassMsg  the value for cust.cust_pass_msg
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustPassMsg(String custPassMsg) {
		this.custPassMsg = custPassMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_pass_msg_answer
	 * @return  the value of cust.cust_pass_msg_answer
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustPassMsgAnswer() {
		return custPassMsgAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_pass_msg_answer
	 * @param custPassMsgAnswer  the value for cust.cust_pass_msg_answer
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustPassMsgAnswer(String custPassMsgAnswer) {
		this.custPassMsgAnswer = custPassMsgAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_email
	 * @return  the value of cust.cust_email
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustEmail() {
		return custEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_email
	 * @param custEmail  the value for cust.cust_email
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_true_name
	 * @return  the value of cust.cust_true_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustTrueName() {
		return custTrueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_true_name
	 * @param custTrueName  the value for cust.cust_true_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustTrueName(String custTrueName) {
		this.custTrueName = custTrueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_identity
	 * @return  the value of cust.cust_identity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustIdentity() {
		return custIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_identity
	 * @param custIdentity  the value for cust.cust_identity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustIdentity(String custIdentity) {
		this.custIdentity = custIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_tel
	 * @return  the value of cust.cust_tel
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustTel() {
		return custTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_tel
	 * @param custTel  the value for cust.cust_tel
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_sex
	 * @return  the value of cust.cust_sex
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustSex() {
		return custSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_sex
	 * @param custSex  the value for cust.cust_sex
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustSex(String custSex) {
		this.custSex = custSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.addr_id
	 * @return  the value of cust.addr_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public Long getAddrId() {
		return addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.addr_id
	 * @param addrId  the value for cust.addr_id
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setAddrId(Long addrId) {
		this.addrId = addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.post_code
	 * @return  the value of cust.post_code
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.post_code
	 * @param postCode  the value for cust.post_code
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.vip_lever
	 * @return  the value of cust.vip_lever
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public Integer getVipLever() {
		return vipLever;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.vip_lever
	 * @param vipLever  the value for cust.vip_lever
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setVipLever(Integer vipLever) {
		this.vipLever = vipLever;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.login_name
	 * @return  the value of cust.login_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.login_name
	 * @param loginName  the value for cust.login_name
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.login_pass
	 * @return  the value of cust.login_pass
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getLoginPass() {
		return loginPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.login_pass
	 * @param loginPass  the value for cust.login_pass
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setLoginPass(String loginPass) {
		this.loginPass = loginPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_role
	 * @return  the value of cust.cust_role
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getCustRole() {
		return custRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_role
	 * @param custRole  the value for cust.cust_role
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setCustRole(String custRole) {
		this.custRole = custRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.register_date
	 * @return  the value of cust.register_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public Date getRegisterDate() {
		return registerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.register_date
	 * @param registerDate  the value for cust.register_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.last_login_date
	 * @return  the value of cust.last_login_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.last_login_date
	 * @param lastLoginDate  the value for cust.last_login_date
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.is_activity
	 * @return  the value of cust.is_activity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public String getIsActivity() {
		return isActivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.is_activity
	 * @param isActivity  the value for cust.is_activity
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	public void setIsActivity(String isActivity) {
		this.isActivity = isActivity;
	}
}