package com.hzq.shop.domain;

import java.util.Date;

public class Custs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.cust_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.cust_pass
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.cust_role
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.register_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custs.last_login_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.cust_id
     *
     * @return the value of custs.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.cust_id
     *
     * @param custId the value for custs.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.cust_name
     *
     * @return the value of custs.cust_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.cust_name
     *
     * @param custName the value for custs.cust_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.cust_pass
     *
     * @return the value of custs.cust_pass
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustPass() {
        return custPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.cust_pass
     *
     * @param custPass the value for custs.cust_pass
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustPass(String custPass) {
        this.custPass = custPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.cust_role
     *
     * @return the value of custs.cust_role
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustRole() {
        return custRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.cust_role
     *
     * @param custRole the value for custs.cust_role
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustRole(String custRole) {
        this.custRole = custRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.register_date
     *
     * @return the value of custs.register_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.register_date
     *
     * @param registerDate the value for custs.register_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custs.last_login_date
     *
     * @return the value of custs.last_login_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custs.last_login_date
     *
     * @param lastLoginDate the value for custs.last_login_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
}