package com.hzq.shop.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CustExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public CustExample() {
		oredCriteria = new ArrayList<Criteria>();
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		public boolean isValid() {
			return criteria.size() > 0;
		}
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		public List<Criterion> getCriteria() {
			return criteria;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}
		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}
		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}
		public Criteria andCustDetailIdIsNull() {
			addCriterion("cust_detail_id is null");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdIsNotNull() {
			addCriterion("cust_detail_id is not null");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdEqualTo(Long value) {
			addCriterion("cust_detail_id =", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdNotEqualTo(Long value) {
			addCriterion("cust_detail_id <>", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdGreaterThan(Long value) {
			addCriterion("cust_detail_id >", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdGreaterThanOrEqualTo(Long value) {
			addCriterion("cust_detail_id >=", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdLessThan(Long value) {
			addCriterion("cust_detail_id <", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdLessThanOrEqualTo(Long value) {
			addCriterion("cust_detail_id <=", value, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdIn(List<Long> values) {
			addCriterion("cust_detail_id in", values, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdNotIn(List<Long> values) {
			addCriterion("cust_detail_id not in", values, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdBetween(Long value1, Long value2) {
			addCriterion("cust_detail_id between", value1, value2, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustDetailIdNotBetween(Long value1, Long value2) {
			addCriterion("cust_detail_id not between", value1, value2, "custDetailId");
			return (Criteria) this;
		}
		public Criteria andCustSstatusIsNull() {
			addCriterion("cust_sstatus is null");
			return (Criteria) this;
		}
		public Criteria andCustSstatusIsNotNull() {
			addCriterion("cust_sstatus is not null");
			return (Criteria) this;
		}
		public Criteria andCustSstatusEqualTo(String value) {
			addCriterion("cust_sstatus =", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusNotEqualTo(String value) {
			addCriterion("cust_sstatus <>", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusGreaterThan(String value) {
			addCriterion("cust_sstatus >", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusGreaterThanOrEqualTo(String value) {
			addCriterion("cust_sstatus >=", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusLessThan(String value) {
			addCriterion("cust_sstatus <", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusLessThanOrEqualTo(String value) {
			addCriterion("cust_sstatus <=", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusLike(String value) {
			addCriterion("cust_sstatus like", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusNotLike(String value) {
			addCriterion("cust_sstatus not like", value, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusIn(List<String> values) {
			addCriterion("cust_sstatus in", values, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusNotIn(List<String> values) {
			addCriterion("cust_sstatus not in", values, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusBetween(String value1, String value2) {
			addCriterion("cust_sstatus between", value1, value2, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustSstatusNotBetween(String value1, String value2) {
			addCriterion("cust_sstatus not between", value1, value2, "custSstatus");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgIsNull() {
			addCriterion("cust_pass_msg is null");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgIsNotNull() {
			addCriterion("cust_pass_msg is not null");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgEqualTo(String value) {
			addCriterion("cust_pass_msg =", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgNotEqualTo(String value) {
			addCriterion("cust_pass_msg <>", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgGreaterThan(String value) {
			addCriterion("cust_pass_msg >", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgGreaterThanOrEqualTo(String value) {
			addCriterion("cust_pass_msg >=", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgLessThan(String value) {
			addCriterion("cust_pass_msg <", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgLessThanOrEqualTo(String value) {
			addCriterion("cust_pass_msg <=", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgLike(String value) {
			addCriterion("cust_pass_msg like", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgNotLike(String value) {
			addCriterion("cust_pass_msg not like", value, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgIn(List<String> values) {
			addCriterion("cust_pass_msg in", values, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgNotIn(List<String> values) {
			addCriterion("cust_pass_msg not in", values, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgBetween(String value1, String value2) {
			addCriterion("cust_pass_msg between", value1, value2, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgNotBetween(String value1, String value2) {
			addCriterion("cust_pass_msg not between", value1, value2, "custPassMsg");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerIsNull() {
			addCriterion("cust_pass_msg_answer is null");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerIsNotNull() {
			addCriterion("cust_pass_msg_answer is not null");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerEqualTo(String value) {
			addCriterion("cust_pass_msg_answer =", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerNotEqualTo(String value) {
			addCriterion("cust_pass_msg_answer <>", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerGreaterThan(String value) {
			addCriterion("cust_pass_msg_answer >", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerGreaterThanOrEqualTo(String value) {
			addCriterion("cust_pass_msg_answer >=", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerLessThan(String value) {
			addCriterion("cust_pass_msg_answer <", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerLessThanOrEqualTo(String value) {
			addCriterion("cust_pass_msg_answer <=", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerLike(String value) {
			addCriterion("cust_pass_msg_answer like", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerNotLike(String value) {
			addCriterion("cust_pass_msg_answer not like", value, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerIn(List<String> values) {
			addCriterion("cust_pass_msg_answer in", values, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerNotIn(List<String> values) {
			addCriterion("cust_pass_msg_answer not in", values, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerBetween(String value1, String value2) {
			addCriterion("cust_pass_msg_answer between", value1, value2, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustPassMsgAnswerNotBetween(String value1, String value2) {
			addCriterion("cust_pass_msg_answer not between", value1, value2, "custPassMsgAnswer");
			return (Criteria) this;
		}
		public Criteria andCustEmailIsNull() {
			addCriterion("cust_email is null");
			return (Criteria) this;
		}
		public Criteria andCustEmailIsNotNull() {
			addCriterion("cust_email is not null");
			return (Criteria) this;
		}
		public Criteria andCustEmailEqualTo(String value) {
			addCriterion("cust_email =", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailNotEqualTo(String value) {
			addCriterion("cust_email <>", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailGreaterThan(String value) {
			addCriterion("cust_email >", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailGreaterThanOrEqualTo(String value) {
			addCriterion("cust_email >=", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailLessThan(String value) {
			addCriterion("cust_email <", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailLessThanOrEqualTo(String value) {
			addCriterion("cust_email <=", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailLike(String value) {
			addCriterion("cust_email like", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailNotLike(String value) {
			addCriterion("cust_email not like", value, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailIn(List<String> values) {
			addCriterion("cust_email in", values, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailNotIn(List<String> values) {
			addCriterion("cust_email not in", values, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailBetween(String value1, String value2) {
			addCriterion("cust_email between", value1, value2, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustEmailNotBetween(String value1, String value2) {
			addCriterion("cust_email not between", value1, value2, "custEmail");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameIsNull() {
			addCriterion("cust_true_name is null");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameIsNotNull() {
			addCriterion("cust_true_name is not null");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameEqualTo(String value) {
			addCriterion("cust_true_name =", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameNotEqualTo(String value) {
			addCriterion("cust_true_name <>", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameGreaterThan(String value) {
			addCriterion("cust_true_name >", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_true_name >=", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameLessThan(String value) {
			addCriterion("cust_true_name <", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameLessThanOrEqualTo(String value) {
			addCriterion("cust_true_name <=", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameLike(String value) {
			addCriterion("cust_true_name like", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameNotLike(String value) {
			addCriterion("cust_true_name not like", value, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameIn(List<String> values) {
			addCriterion("cust_true_name in", values, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameNotIn(List<String> values) {
			addCriterion("cust_true_name not in", values, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameBetween(String value1, String value2) {
			addCriterion("cust_true_name between", value1, value2, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustTrueNameNotBetween(String value1, String value2) {
			addCriterion("cust_true_name not between", value1, value2, "custTrueName");
			return (Criteria) this;
		}
		public Criteria andCustIdentityIsNull() {
			addCriterion("cust_identity is null");
			return (Criteria) this;
		}
		public Criteria andCustIdentityIsNotNull() {
			addCriterion("cust_identity is not null");
			return (Criteria) this;
		}
		public Criteria andCustIdentityEqualTo(String value) {
			addCriterion("cust_identity =", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityNotEqualTo(String value) {
			addCriterion("cust_identity <>", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityGreaterThan(String value) {
			addCriterion("cust_identity >", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityGreaterThanOrEqualTo(String value) {
			addCriterion("cust_identity >=", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityLessThan(String value) {
			addCriterion("cust_identity <", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityLessThanOrEqualTo(String value) {
			addCriterion("cust_identity <=", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityLike(String value) {
			addCriterion("cust_identity like", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityNotLike(String value) {
			addCriterion("cust_identity not like", value, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityIn(List<String> values) {
			addCriterion("cust_identity in", values, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityNotIn(List<String> values) {
			addCriterion("cust_identity not in", values, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityBetween(String value1, String value2) {
			addCriterion("cust_identity between", value1, value2, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustIdentityNotBetween(String value1, String value2) {
			addCriterion("cust_identity not between", value1, value2, "custIdentity");
			return (Criteria) this;
		}
		public Criteria andCustTelIsNull() {
			addCriterion("cust_tel is null");
			return (Criteria) this;
		}
		public Criteria andCustTelIsNotNull() {
			addCriterion("cust_tel is not null");
			return (Criteria) this;
		}
		public Criteria andCustTelEqualTo(String value) {
			addCriterion("cust_tel =", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelNotEqualTo(String value) {
			addCriterion("cust_tel <>", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelGreaterThan(String value) {
			addCriterion("cust_tel >", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelGreaterThanOrEqualTo(String value) {
			addCriterion("cust_tel >=", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelLessThan(String value) {
			addCriterion("cust_tel <", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelLessThanOrEqualTo(String value) {
			addCriterion("cust_tel <=", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelLike(String value) {
			addCriterion("cust_tel like", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelNotLike(String value) {
			addCriterion("cust_tel not like", value, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelIn(List<String> values) {
			addCriterion("cust_tel in", values, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelNotIn(List<String> values) {
			addCriterion("cust_tel not in", values, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelBetween(String value1, String value2) {
			addCriterion("cust_tel between", value1, value2, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustTelNotBetween(String value1, String value2) {
			addCriterion("cust_tel not between", value1, value2, "custTel");
			return (Criteria) this;
		}
		public Criteria andCustSexIsNull() {
			addCriterion("cust_sex is null");
			return (Criteria) this;
		}
		public Criteria andCustSexIsNotNull() {
			addCriterion("cust_sex is not null");
			return (Criteria) this;
		}
		public Criteria andCustSexEqualTo(String value) {
			addCriterion("cust_sex =", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexNotEqualTo(String value) {
			addCriterion("cust_sex <>", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexGreaterThan(String value) {
			addCriterion("cust_sex >", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexGreaterThanOrEqualTo(String value) {
			addCriterion("cust_sex >=", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexLessThan(String value) {
			addCriterion("cust_sex <", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexLessThanOrEqualTo(String value) {
			addCriterion("cust_sex <=", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexLike(String value) {
			addCriterion("cust_sex like", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexNotLike(String value) {
			addCriterion("cust_sex not like", value, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexIn(List<String> values) {
			addCriterion("cust_sex in", values, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexNotIn(List<String> values) {
			addCriterion("cust_sex not in", values, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexBetween(String value1, String value2) {
			addCriterion("cust_sex between", value1, value2, "custSex");
			return (Criteria) this;
		}
		public Criteria andCustSexNotBetween(String value1, String value2) {
			addCriterion("cust_sex not between", value1, value2, "custSex");
			return (Criteria) this;
		}
		public Criteria andAddrIdIsNull() {
			addCriterion("addr_id is null");
			return (Criteria) this;
		}
		public Criteria andAddrIdIsNotNull() {
			addCriterion("addr_id is not null");
			return (Criteria) this;
		}
		public Criteria andAddrIdEqualTo(Long value) {
			addCriterion("addr_id =", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdNotEqualTo(Long value) {
			addCriterion("addr_id <>", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdGreaterThan(Long value) {
			addCriterion("addr_id >", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdGreaterThanOrEqualTo(Long value) {
			addCriterion("addr_id >=", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdLessThan(Long value) {
			addCriterion("addr_id <", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdLessThanOrEqualTo(Long value) {
			addCriterion("addr_id <=", value, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdIn(List<Long> values) {
			addCriterion("addr_id in", values, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdNotIn(List<Long> values) {
			addCriterion("addr_id not in", values, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdBetween(Long value1, Long value2) {
			addCriterion("addr_id between", value1, value2, "addrId");
			return (Criteria) this;
		}
		public Criteria andAddrIdNotBetween(Long value1, Long value2) {
			addCriterion("addr_id not between", value1, value2, "addrId");
			return (Criteria) this;
		}
		public Criteria andPostCodeIsNull() {
			addCriterion("post_code is null");
			return (Criteria) this;
		}
		public Criteria andPostCodeIsNotNull() {
			addCriterion("post_code is not null");
			return (Criteria) this;
		}
		public Criteria andPostCodeEqualTo(String value) {
			addCriterion("post_code =", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeNotEqualTo(String value) {
			addCriterion("post_code <>", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeGreaterThan(String value) {
			addCriterion("post_code >", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
			addCriterion("post_code >=", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeLessThan(String value) {
			addCriterion("post_code <", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeLessThanOrEqualTo(String value) {
			addCriterion("post_code <=", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeLike(String value) {
			addCriterion("post_code like", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeNotLike(String value) {
			addCriterion("post_code not like", value, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeIn(List<String> values) {
			addCriterion("post_code in", values, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeNotIn(List<String> values) {
			addCriterion("post_code not in", values, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeBetween(String value1, String value2) {
			addCriterion("post_code between", value1, value2, "postCode");
			return (Criteria) this;
		}
		public Criteria andPostCodeNotBetween(String value1, String value2) {
			addCriterion("post_code not between", value1, value2, "postCode");
			return (Criteria) this;
		}
		public Criteria andVipLeverIsNull() {
			addCriterion("vip_lever is null");
			return (Criteria) this;
		}
		public Criteria andVipLeverIsNotNull() {
			addCriterion("vip_lever is not null");
			return (Criteria) this;
		}
		public Criteria andVipLeverEqualTo(Integer value) {
			addCriterion("vip_lever =", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverNotEqualTo(Integer value) {
			addCriterion("vip_lever <>", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverGreaterThan(Integer value) {
			addCriterion("vip_lever >", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverGreaterThanOrEqualTo(Integer value) {
			addCriterion("vip_lever >=", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverLessThan(Integer value) {
			addCriterion("vip_lever <", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverLessThanOrEqualTo(Integer value) {
			addCriterion("vip_lever <=", value, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverIn(List<Integer> values) {
			addCriterion("vip_lever in", values, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverNotIn(List<Integer> values) {
			addCriterion("vip_lever not in", values, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverBetween(Integer value1, Integer value2) {
			addCriterion("vip_lever between", value1, value2, "vipLever");
			return (Criteria) this;
		}
		public Criteria andVipLeverNotBetween(Integer value1, Integer value2) {
			addCriterion("vip_lever not between", value1, value2, "vipLever");
			return (Criteria) this;
		}
		public Criteria andLoginNameIsNull() {
			addCriterion("login_name is null");
			return (Criteria) this;
		}
		public Criteria andLoginNameIsNotNull() {
			addCriterion("login_name is not null");
			return (Criteria) this;
		}
		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("login_name =", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("login_name <>", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("login_name >", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("login_name >=", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameLessThan(String value) {
			addCriterion("login_name <", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("login_name <=", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameLike(String value) {
			addCriterion("login_name like", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameNotLike(String value) {
			addCriterion("login_name not like", value, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("login_name in", values, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("login_name not in", values, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("login_name between", value1, value2, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("login_name not between", value1, value2, "loginName");
			return (Criteria) this;
		}
		public Criteria andLoginPassIsNull() {
			addCriterion("login_pass is null");
			return (Criteria) this;
		}
		public Criteria andLoginPassIsNotNull() {
			addCriterion("login_pass is not null");
			return (Criteria) this;
		}
		public Criteria andLoginPassEqualTo(String value) {
			addCriterion("login_pass =", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassNotEqualTo(String value) {
			addCriterion("login_pass <>", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassGreaterThan(String value) {
			addCriterion("login_pass >", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassGreaterThanOrEqualTo(String value) {
			addCriterion("login_pass >=", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassLessThan(String value) {
			addCriterion("login_pass <", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassLessThanOrEqualTo(String value) {
			addCriterion("login_pass <=", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassLike(String value) {
			addCriterion("login_pass like", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassNotLike(String value) {
			addCriterion("login_pass not like", value, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassIn(List<String> values) {
			addCriterion("login_pass in", values, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassNotIn(List<String> values) {
			addCriterion("login_pass not in", values, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassBetween(String value1, String value2) {
			addCriterion("login_pass between", value1, value2, "loginPass");
			return (Criteria) this;
		}
		public Criteria andLoginPassNotBetween(String value1, String value2) {
			addCriterion("login_pass not between", value1, value2, "loginPass");
			return (Criteria) this;
		}
		public Criteria andCustRoleIsNull() {
			addCriterion("cust_role is null");
			return (Criteria) this;
		}
		public Criteria andCustRoleIsNotNull() {
			addCriterion("cust_role is not null");
			return (Criteria) this;
		}
		public Criteria andCustRoleEqualTo(String value) {
			addCriterion("cust_role =", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleNotEqualTo(String value) {
			addCriterion("cust_role <>", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleGreaterThan(String value) {
			addCriterion("cust_role >", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleGreaterThanOrEqualTo(String value) {
			addCriterion("cust_role >=", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleLessThan(String value) {
			addCriterion("cust_role <", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleLessThanOrEqualTo(String value) {
			addCriterion("cust_role <=", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleLike(String value) {
			addCriterion("cust_role like", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleNotLike(String value) {
			addCriterion("cust_role not like", value, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleIn(List<String> values) {
			addCriterion("cust_role in", values, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleNotIn(List<String> values) {
			addCriterion("cust_role not in", values, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleBetween(String value1, String value2) {
			addCriterion("cust_role between", value1, value2, "custRole");
			return (Criteria) this;
		}
		public Criteria andCustRoleNotBetween(String value1, String value2) {
			addCriterion("cust_role not between", value1, value2, "custRole");
			return (Criteria) this;
		}
		public Criteria andRegisterDateIsNull() {
			addCriterion("register_date is null");
			return (Criteria) this;
		}
		public Criteria andRegisterDateIsNotNull() {
			addCriterion("register_date is not null");
			return (Criteria) this;
		}
		public Criteria andRegisterDateEqualTo(Date value) {
			addCriterionForJDBCDate("register_date =", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("register_date <>", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateGreaterThan(Date value) {
			addCriterionForJDBCDate("register_date >", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("register_date >=", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateLessThan(Date value) {
			addCriterionForJDBCDate("register_date <", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("register_date <=", value, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateIn(List<Date> values) {
			addCriterionForJDBCDate("register_date in", values, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("register_date not in", values, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("register_date between", value1, value2, "registerDate");
			return (Criteria) this;
		}
		public Criteria andRegisterDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("register_date not between", value1, value2, "registerDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateIsNull() {
			addCriterion("last_login_date is null");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateIsNotNull() {
			addCriterion("last_login_date is not null");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateEqualTo(Date value) {
			addCriterionForJDBCDate("last_login_date =", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("last_login_date <>", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateGreaterThan(Date value) {
			addCriterionForJDBCDate("last_login_date >", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_login_date >=", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateLessThan(Date value) {
			addCriterionForJDBCDate("last_login_date <", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_login_date <=", value, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateIn(List<Date> values) {
			addCriterionForJDBCDate("last_login_date in", values, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("last_login_date not in", values, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_login_date between", value1, value2, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andLastLoginDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_login_date not between", value1, value2, "lastLoginDate");
			return (Criteria) this;
		}
		public Criteria andIsActivityIsNull() {
			addCriterion("is_activity is null");
			return (Criteria) this;
		}
		public Criteria andIsActivityIsNotNull() {
			addCriterion("is_activity is not null");
			return (Criteria) this;
		}
		public Criteria andIsActivityEqualTo(String value) {
			addCriterion("is_activity =", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityNotEqualTo(String value) {
			addCriterion("is_activity <>", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityGreaterThan(String value) {
			addCriterion("is_activity >", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityGreaterThanOrEqualTo(String value) {
			addCriterion("is_activity >=", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityLessThan(String value) {
			addCriterion("is_activity <", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityLessThanOrEqualTo(String value) {
			addCriterion("is_activity <=", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityLike(String value) {
			addCriterion("is_activity like", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityNotLike(String value) {
			addCriterion("is_activity not like", value, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityIn(List<String> values) {
			addCriterion("is_activity in", values, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityNotIn(List<String> values) {
			addCriterion("is_activity not in", values, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityBetween(String value1, String value2) {
			addCriterion("is_activity between", value1, value2, "isActivity");
			return (Criteria) this;
		}
		public Criteria andIsActivityNotBetween(String value1, String value2) {
			addCriterion("is_activity not between", value1, value2, "isActivity");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * cust
	 * @mbggenerated Sun Oct 16 10:18:33 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}
		public Object getValue() {
			return value;
		}
		public Object getSecondValue() {
			return secondValue;
		}
		public boolean isNoValue() {
			return noValue;
		}
		public boolean isSingleValue() {
			return singleValue;
		}
		public boolean isBetweenValue() {
			return betweenValue;
		}
		public boolean isListValue() {
			return listValue;
		}
		public String getTypeHandler() {
			return typeHandler;
		}
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * cust
	 * @mbggenerated do_not_delete_during_merge Sun Oct 16 10:02:54 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}
}
