package com.hzq.shop.domain;

public class CustDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_sstatus
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custSstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_pass_msg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custPassMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_pass_msg_answer
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custPassMsgAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_email
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_true_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custTrueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_identity
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.cust_sex
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String custSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.post_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_detail.vip_lever
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Integer vipLever;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_detail_id
     *
     * @return the value of cust_detail.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustDetailId() {
        return custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_detail_id
     *
     * @param custDetailId the value for cust_detail.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustDetailId(Long custDetailId) {
        this.custDetailId = custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_id
     *
     * @return the value of cust_detail.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_id
     *
     * @param custId the value for cust_detail.cust_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_sstatus
     *
     * @return the value of cust_detail.cust_sstatus
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustSstatus() {
        return custSstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_sstatus
     *
     * @param custSstatus the value for cust_detail.cust_sstatus
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustSstatus(String custSstatus) {
        this.custSstatus = custSstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_pass_msg
     *
     * @return the value of cust_detail.cust_pass_msg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustPassMsg() {
        return custPassMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_pass_msg
     *
     * @param custPassMsg the value for cust_detail.cust_pass_msg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustPassMsg(String custPassMsg) {
        this.custPassMsg = custPassMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_pass_msg_answer
     *
     * @return the value of cust_detail.cust_pass_msg_answer
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustPassMsgAnswer() {
        return custPassMsgAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_pass_msg_answer
     *
     * @param custPassMsgAnswer the value for cust_detail.cust_pass_msg_answer
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustPassMsgAnswer(String custPassMsgAnswer) {
        this.custPassMsgAnswer = custPassMsgAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_email
     *
     * @return the value of cust_detail.cust_email
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustEmail() {
        return custEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_email
     *
     * @param custEmail the value for cust_detail.cust_email
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustEmail(String custEmail) {
        this.custEmail = custEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_true_name
     *
     * @return the value of cust_detail.cust_true_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustTrueName() {
        return custTrueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_true_name
     *
     * @param custTrueName the value for cust_detail.cust_true_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustTrueName(String custTrueName) {
        this.custTrueName = custTrueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_identity
     *
     * @return the value of cust_detail.cust_identity
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustIdentity() {
        return custIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_identity
     *
     * @param custIdentity the value for cust_detail.cust_identity
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustIdentity(String custIdentity) {
        this.custIdentity = custIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_tel
     *
     * @return the value of cust_detail.cust_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_tel
     *
     * @param custTel the value for cust_detail.cust_tel
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.cust_sex
     *
     * @return the value of cust_detail.cust_sex
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getCustSex() {
        return custSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.cust_sex
     *
     * @param custSex the value for cust_detail.cust_sex
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustSex(String custSex) {
        this.custSex = custSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.addr_id
     *
     * @return the value of cust_detail.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.addr_id
     *
     * @param addrId the value for cust_detail.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.post_code
     *
     * @return the value of cust_detail.post_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.post_code
     *
     * @param postCode the value for cust_detail.post_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_detail.vip_lever
     *
     * @return the value of cust_detail.vip_lever
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Integer getVipLever() {
        return vipLever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_detail.vip_lever
     *
     * @param vipLever the value for cust_detail.vip_lever
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setVipLever(Integer vipLever) {
        this.vipLever = vipLever;
    }
}