package com.hzq.shop.domain;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.point_discount
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Float pointDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long addrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_code
     *
     * @return the value of orders.order_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_code
     *
     * @param orderCode the value for orders.order_code
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.point_discount
     *
     * @return the value of orders.point_discount
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Float getPointDiscount() {
        return pointDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.point_discount
     *
     * @param pointDiscount the value for orders.point_discount
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setPointDiscount(Float pointDiscount) {
        this.pointDiscount = pointDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_date
     *
     * @return the value of orders.order_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_date
     *
     * @param orderDate the value for orders.order_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cust_detail_id
     *
     * @return the value of orders.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustDetailId() {
        return custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cust_detail_id
     *
     * @param custDetailId the value for orders.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustDetailId(Long custDetailId) {
        this.custDetailId = custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.addr_id
     *
     * @return the value of orders.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.addr_id
     *
     * @param addrId the value for orders.addr_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }
}