package com.hzq.shop.domain;

import java.util.Date;

public class ProductMessg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_status
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String prodStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_publish_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date prodPublishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String prodPhotoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Float prodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_vip_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Float prodVipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Integer prodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_unit
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String prodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_introduction
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String prodIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_start_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date prodStartSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_stop_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date prodStopSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_messg.prod_points
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Integer prodPoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_id
     *
     * @return the value of product_messg.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_id
     *
     * @param prodId the value for product_messg.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_name
     *
     * @return the value of product_messg.prod_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_name
     *
     * @param prodName the value for product_messg.prod_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_status
     *
     * @return the value of product_messg.prod_status
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProdStatus() {
        return prodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_status
     *
     * @param prodStatus the value for product_messg.prod_status
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdStatus(String prodStatus) {
        this.prodStatus = prodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.sort_id
     *
     * @return the value of product_messg.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.sort_id
     *
     * @param sortId the value for product_messg.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setSortId(Long sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_publish_date
     *
     * @return the value of product_messg.prod_publish_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getProdPublishDate() {
        return prodPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_publish_date
     *
     * @param prodPublishDate the value for product_messg.prod_publish_date
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdPublishDate(Date prodPublishDate) {
        this.prodPublishDate = prodPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_photo_url
     *
     * @return the value of product_messg.prod_photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProdPhotoUrl() {
        return prodPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_photo_url
     *
     * @param prodPhotoUrl the value for product_messg.prod_photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdPhotoUrl(String prodPhotoUrl) {
        this.prodPhotoUrl = prodPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_price
     *
     * @return the value of product_messg.prod_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Float getProdPrice() {
        return prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_price
     *
     * @param prodPrice the value for product_messg.prod_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdPrice(Float prodPrice) {
        this.prodPrice = prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_vip_price
     *
     * @return the value of product_messg.prod_vip_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Float getProdVipPrice() {
        return prodVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_vip_price
     *
     * @param prodVipPrice the value for product_messg.prod_vip_price
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdVipPrice(Float prodVipPrice) {
        this.prodVipPrice = prodVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_num
     *
     * @return the value of product_messg.prod_num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Integer getProdNum() {
        return prodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_num
     *
     * @param prodNum the value for product_messg.prod_num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdNum(Integer prodNum) {
        this.prodNum = prodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_unit
     *
     * @return the value of product_messg.prod_unit
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProdUnit() {
        return prodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_unit
     *
     * @param prodUnit the value for product_messg.prod_unit
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdUnit(String prodUnit) {
        this.prodUnit = prodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_introduction
     *
     * @return the value of product_messg.prod_introduction
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getProdIntroduction() {
        return prodIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_introduction
     *
     * @param prodIntroduction the value for product_messg.prod_introduction
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdIntroduction(String prodIntroduction) {
        this.prodIntroduction = prodIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_start_sale
     *
     * @return the value of product_messg.prod_start_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getProdStartSale() {
        return prodStartSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_start_sale
     *
     * @param prodStartSale the value for product_messg.prod_start_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdStartSale(Date prodStartSale) {
        this.prodStartSale = prodStartSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_stop_sale
     *
     * @return the value of product_messg.prod_stop_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getProdStopSale() {
        return prodStopSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_stop_sale
     *
     * @param prodStopSale the value for product_messg.prod_stop_sale
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdStopSale(Date prodStopSale) {
        this.prodStopSale = prodStopSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_messg.prod_points
     *
     * @return the value of product_messg.prod_points
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Integer getProdPoints() {
        return prodPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_messg.prod_points
     *
     * @param prodPoints the value for product_messg.prod_points
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdPoints(Integer prodPoints) {
        this.prodPoints = prodPoints;
    }
}