package com.hzq.shop.domain;

public class ProductSort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sort.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sort.sort_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String sortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sort.sort_desc
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String sortDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sort.parent_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sort.sort_id
     *
     * @return the value of product_sort.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sort.sort_id
     *
     * @param sortId the value for product_sort.sort_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setSortId(Long sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sort.sort_name
     *
     * @return the value of product_sort.sort_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sort.sort_name
     *
     * @param sortName the value for product_sort.sort_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setSortName(String sortName) {
        this.sortName = sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sort.sort_desc
     *
     * @return the value of product_sort.sort_desc
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getSortDesc() {
        return sortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sort.sort_desc
     *
     * @param sortDesc the value for product_sort.sort_desc
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setSortDesc(String sortDesc) {
        this.sortDesc = sortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sort.parent_id
     *
     * @return the value of product_sort.parent_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sort.parent_id
     *
     * @param parentId the value for product_sort.parent_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}