package com.hzq.shop.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProductMessgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public ProductMessgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProdIdIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(Long value) {
            addCriterion("prod_id =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(Long value) {
            addCriterion("prod_id <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(Long value) {
            addCriterion("prod_id >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prod_id >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(Long value) {
            addCriterion("prod_id <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(Long value) {
            addCriterion("prod_id <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<Long> values) {
            addCriterion("prod_id in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<Long> values) {
            addCriterion("prod_id not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(Long value1, Long value2) {
            addCriterion("prod_id between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(Long value1, Long value2) {
            addCriterion("prod_id not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNull() {
            addCriterion("prod_name is null");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNotNull() {
            addCriterion("prod_name is not null");
            return (Criteria) this;
        }

        public Criteria andProdNameEqualTo(String value) {
            addCriterion("prod_name =", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotEqualTo(String value) {
            addCriterion("prod_name <>", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThan(String value) {
            addCriterion("prod_name >", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThanOrEqualTo(String value) {
            addCriterion("prod_name >=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThan(String value) {
            addCriterion("prod_name <", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThanOrEqualTo(String value) {
            addCriterion("prod_name <=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLike(String value) {
            addCriterion("prod_name like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotLike(String value) {
            addCriterion("prod_name not like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameIn(List<String> values) {
            addCriterion("prod_name in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotIn(List<String> values) {
            addCriterion("prod_name not in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameBetween(String value1, String value2) {
            addCriterion("prod_name between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotBetween(String value1, String value2) {
            addCriterion("prod_name not between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdStatusIsNull() {
            addCriterion("prod_status is null");
            return (Criteria) this;
        }

        public Criteria andProdStatusIsNotNull() {
            addCriterion("prod_status is not null");
            return (Criteria) this;
        }

        public Criteria andProdStatusEqualTo(String value) {
            addCriterion("prod_status =", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotEqualTo(String value) {
            addCriterion("prod_status <>", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusGreaterThan(String value) {
            addCriterion("prod_status >", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusGreaterThanOrEqualTo(String value) {
            addCriterion("prod_status >=", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLessThan(String value) {
            addCriterion("prod_status <", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLessThanOrEqualTo(String value) {
            addCriterion("prod_status <=", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLike(String value) {
            addCriterion("prod_status like", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotLike(String value) {
            addCriterion("prod_status not like", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusIn(List<String> values) {
            addCriterion("prod_status in", values, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotIn(List<String> values) {
            addCriterion("prod_status not in", values, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusBetween(String value1, String value2) {
            addCriterion("prod_status between", value1, value2, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotBetween(String value1, String value2) {
            addCriterion("prod_status not between", value1, value2, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNull() {
            addCriterion("sort_id is null");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNotNull() {
            addCriterion("sort_id is not null");
            return (Criteria) this;
        }

        public Criteria andSortIdEqualTo(Long value) {
            addCriterion("sort_id =", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotEqualTo(Long value) {
            addCriterion("sort_id <>", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThan(Long value) {
            addCriterion("sort_id >", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sort_id >=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThan(Long value) {
            addCriterion("sort_id <", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThanOrEqualTo(Long value) {
            addCriterion("sort_id <=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdIn(List<Long> values) {
            addCriterion("sort_id in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotIn(List<Long> values) {
            addCriterion("sort_id not in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdBetween(Long value1, Long value2) {
            addCriterion("sort_id between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotBetween(Long value1, Long value2) {
            addCriterion("sort_id not between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateIsNull() {
            addCriterion("prod_publish_date is null");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateIsNotNull() {
            addCriterion("prod_publish_date is not null");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateEqualTo(Date value) {
            addCriterionForJDBCDate("prod_publish_date =", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("prod_publish_date <>", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateGreaterThan(Date value) {
            addCriterionForJDBCDate("prod_publish_date >", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_publish_date >=", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateLessThan(Date value) {
            addCriterionForJDBCDate("prod_publish_date <", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_publish_date <=", value, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateIn(List<Date> values) {
            addCriterionForJDBCDate("prod_publish_date in", values, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("prod_publish_date not in", values, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_publish_date between", value1, value2, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPublishDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_publish_date not between", value1, value2, "prodPublishDate");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlIsNull() {
            addCriterion("prod_photo_url is null");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlIsNotNull() {
            addCriterion("prod_photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlEqualTo(String value) {
            addCriterion("prod_photo_url =", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlNotEqualTo(String value) {
            addCriterion("prod_photo_url <>", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlGreaterThan(String value) {
            addCriterion("prod_photo_url >", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("prod_photo_url >=", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlLessThan(String value) {
            addCriterion("prod_photo_url <", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("prod_photo_url <=", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlLike(String value) {
            addCriterion("prod_photo_url like", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlNotLike(String value) {
            addCriterion("prod_photo_url not like", value, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlIn(List<String> values) {
            addCriterion("prod_photo_url in", values, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlNotIn(List<String> values) {
            addCriterion("prod_photo_url not in", values, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlBetween(String value1, String value2) {
            addCriterion("prod_photo_url between", value1, value2, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("prod_photo_url not between", value1, value2, "prodPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andProdPriceIsNull() {
            addCriterion("prod_price is null");
            return (Criteria) this;
        }

        public Criteria andProdPriceIsNotNull() {
            addCriterion("prod_price is not null");
            return (Criteria) this;
        }

        public Criteria andProdPriceEqualTo(Float value) {
            addCriterion("prod_price =", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceNotEqualTo(Float value) {
            addCriterion("prod_price <>", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceGreaterThan(Float value) {
            addCriterion("prod_price >", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("prod_price >=", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceLessThan(Float value) {
            addCriterion("prod_price <", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceLessThanOrEqualTo(Float value) {
            addCriterion("prod_price <=", value, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceIn(List<Float> values) {
            addCriterion("prod_price in", values, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceNotIn(List<Float> values) {
            addCriterion("prod_price not in", values, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceBetween(Float value1, Float value2) {
            addCriterion("prod_price between", value1, value2, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdPriceNotBetween(Float value1, Float value2) {
            addCriterion("prod_price not between", value1, value2, "prodPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceIsNull() {
            addCriterion("prod_vip_price is null");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceIsNotNull() {
            addCriterion("prod_vip_price is not null");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceEqualTo(Float value) {
            addCriterion("prod_vip_price =", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceNotEqualTo(Float value) {
            addCriterion("prod_vip_price <>", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceGreaterThan(Float value) {
            addCriterion("prod_vip_price >", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("prod_vip_price >=", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceLessThan(Float value) {
            addCriterion("prod_vip_price <", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceLessThanOrEqualTo(Float value) {
            addCriterion("prod_vip_price <=", value, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceIn(List<Float> values) {
            addCriterion("prod_vip_price in", values, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceNotIn(List<Float> values) {
            addCriterion("prod_vip_price not in", values, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceBetween(Float value1, Float value2) {
            addCriterion("prod_vip_price between", value1, value2, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdVipPriceNotBetween(Float value1, Float value2) {
            addCriterion("prod_vip_price not between", value1, value2, "prodVipPrice");
            return (Criteria) this;
        }

        public Criteria andProdNumIsNull() {
            addCriterion("prod_num is null");
            return (Criteria) this;
        }

        public Criteria andProdNumIsNotNull() {
            addCriterion("prod_num is not null");
            return (Criteria) this;
        }

        public Criteria andProdNumEqualTo(Integer value) {
            addCriterion("prod_num =", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotEqualTo(Integer value) {
            addCriterion("prod_num <>", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumGreaterThan(Integer value) {
            addCriterion("prod_num >", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("prod_num >=", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumLessThan(Integer value) {
            addCriterion("prod_num <", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumLessThanOrEqualTo(Integer value) {
            addCriterion("prod_num <=", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumIn(List<Integer> values) {
            addCriterion("prod_num in", values, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotIn(List<Integer> values) {
            addCriterion("prod_num not in", values, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumBetween(Integer value1, Integer value2) {
            addCriterion("prod_num between", value1, value2, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotBetween(Integer value1, Integer value2) {
            addCriterion("prod_num not between", value1, value2, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdUnitIsNull() {
            addCriterion("prod_unit is null");
            return (Criteria) this;
        }

        public Criteria andProdUnitIsNotNull() {
            addCriterion("prod_unit is not null");
            return (Criteria) this;
        }

        public Criteria andProdUnitEqualTo(String value) {
            addCriterion("prod_unit =", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitNotEqualTo(String value) {
            addCriterion("prod_unit <>", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitGreaterThan(String value) {
            addCriterion("prod_unit >", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitGreaterThanOrEqualTo(String value) {
            addCriterion("prod_unit >=", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitLessThan(String value) {
            addCriterion("prod_unit <", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitLessThanOrEqualTo(String value) {
            addCriterion("prod_unit <=", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitLike(String value) {
            addCriterion("prod_unit like", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitNotLike(String value) {
            addCriterion("prod_unit not like", value, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitIn(List<String> values) {
            addCriterion("prod_unit in", values, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitNotIn(List<String> values) {
            addCriterion("prod_unit not in", values, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitBetween(String value1, String value2) {
            addCriterion("prod_unit between", value1, value2, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdUnitNotBetween(String value1, String value2) {
            addCriterion("prod_unit not between", value1, value2, "prodUnit");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionIsNull() {
            addCriterion("prod_introduction is null");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionIsNotNull() {
            addCriterion("prod_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionEqualTo(String value) {
            addCriterion("prod_introduction =", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionNotEqualTo(String value) {
            addCriterion("prod_introduction <>", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionGreaterThan(String value) {
            addCriterion("prod_introduction >", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("prod_introduction >=", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionLessThan(String value) {
            addCriterion("prod_introduction <", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionLessThanOrEqualTo(String value) {
            addCriterion("prod_introduction <=", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionLike(String value) {
            addCriterion("prod_introduction like", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionNotLike(String value) {
            addCriterion("prod_introduction not like", value, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionIn(List<String> values) {
            addCriterion("prod_introduction in", values, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionNotIn(List<String> values) {
            addCriterion("prod_introduction not in", values, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionBetween(String value1, String value2) {
            addCriterion("prod_introduction between", value1, value2, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdIntroductionNotBetween(String value1, String value2) {
            addCriterion("prod_introduction not between", value1, value2, "prodIntroduction");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleIsNull() {
            addCriterion("prod_start_sale is null");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleIsNotNull() {
            addCriterion("prod_start_sale is not null");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleEqualTo(Date value) {
            addCriterionForJDBCDate("prod_start_sale =", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleNotEqualTo(Date value) {
            addCriterionForJDBCDate("prod_start_sale <>", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleGreaterThan(Date value) {
            addCriterionForJDBCDate("prod_start_sale >", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_start_sale >=", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleLessThan(Date value) {
            addCriterionForJDBCDate("prod_start_sale <", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_start_sale <=", value, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleIn(List<Date> values) {
            addCriterionForJDBCDate("prod_start_sale in", values, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleNotIn(List<Date> values) {
            addCriterionForJDBCDate("prod_start_sale not in", values, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_start_sale between", value1, value2, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStartSaleNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_start_sale not between", value1, value2, "prodStartSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleIsNull() {
            addCriterion("prod_stop_sale is null");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleIsNotNull() {
            addCriterion("prod_stop_sale is not null");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleEqualTo(Date value) {
            addCriterionForJDBCDate("prod_stop_sale =", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleNotEqualTo(Date value) {
            addCriterionForJDBCDate("prod_stop_sale <>", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleGreaterThan(Date value) {
            addCriterionForJDBCDate("prod_stop_sale >", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_stop_sale >=", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleLessThan(Date value) {
            addCriterionForJDBCDate("prod_stop_sale <", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_stop_sale <=", value, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleIn(List<Date> values) {
            addCriterionForJDBCDate("prod_stop_sale in", values, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleNotIn(List<Date> values) {
            addCriterionForJDBCDate("prod_stop_sale not in", values, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_stop_sale between", value1, value2, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdStopSaleNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_stop_sale not between", value1, value2, "prodStopSale");
            return (Criteria) this;
        }

        public Criteria andProdPointsIsNull() {
            addCriterion("prod_points is null");
            return (Criteria) this;
        }

        public Criteria andProdPointsIsNotNull() {
            addCriterion("prod_points is not null");
            return (Criteria) this;
        }

        public Criteria andProdPointsEqualTo(Integer value) {
            addCriterion("prod_points =", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsNotEqualTo(Integer value) {
            addCriterion("prod_points <>", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsGreaterThan(Integer value) {
            addCriterion("prod_points >", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("prod_points >=", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsLessThan(Integer value) {
            addCriterion("prod_points <", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsLessThanOrEqualTo(Integer value) {
            addCriterion("prod_points <=", value, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsIn(List<Integer> values) {
            addCriterion("prod_points in", values, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsNotIn(List<Integer> values) {
            addCriterion("prod_points not in", values, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsBetween(Integer value1, Integer value2) {
            addCriterion("prod_points between", value1, value2, "prodPoints");
            return (Criteria) this;
        }

        public Criteria andProdPointsNotBetween(Integer value1, Integer value2) {
            addCriterion("prod_points not between", value1, value2, "prodPoints");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_messg
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 27 23:01:23 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}