package com.hzq.shop.domain;

public class ProductPhotos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_photos.photo_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_photos.photo_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String photoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_photos.photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_photos.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long prodId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_photos.photo_id
     *
     * @return the value of product_photos.photo_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_photos.photo_id
     *
     * @param photoId the value for product_photos.photo_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_photos.photo_name
     *
     * @return the value of product_photos.photo_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_photos.photo_name
     *
     * @param photoName the value for product_photos.photo_name
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_photos.photo_url
     *
     * @return the value of product_photos.photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_photos.photo_url
     *
     * @param photoUrl the value for product_photos.photo_url
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_photos.prod_id
     *
     * @return the value of product_photos.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_photos.prod_id
     *
     * @param prodId the value for product_photos.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }
}