package com.hzq.shop.domain;

import java.util.Date;

public class ShopCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.cart_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long cartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long custDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.add_time
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.cart_id
     *
     * @return the value of shop_car.cart_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.cart_id
     *
     * @param cartId the value for shop_car.cart_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.cust_detail_id
     *
     * @return the value of shop_car.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getCustDetailId() {
        return custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.cust_detail_id
     *
     * @param custDetailId the value for shop_car.cust_detail_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setCustDetailId(Long custDetailId) {
        this.custDetailId = custDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.prod_id
     *
     * @return the value of shop_car.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.prod_id
     *
     * @param prodId the value for shop_car.prod_id
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.num
     *
     * @return the value of shop_car.num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.num
     *
     * @param num the value for shop_car.num
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.add_time
     *
     * @return the value of shop_car.add_time
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.add_time
     *
     * @param addTime the value for shop_car.add_time
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}