package com.hzq.shop.domain;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private Long staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_code
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private String staffCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.login_pass
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private String loginPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_email
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private String staffEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_sex
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private String staffSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.register_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.last_login_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_code
     *
     * @return the value of staff.staff_code
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_code
     *
     * @param staffCode the value for staff.staff_code
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.login_pass
     *
     * @return the value of staff.login_pass
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public String getLoginPass() {
        return loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.login_pass
     *
     * @param loginPass the value for staff.login_pass
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_email
     *
     * @return the value of staff.staff_email
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public String getStaffEmail() {
        return staffEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_email
     *
     * @param staffEmail the value for staff.staff_email
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setStaffEmail(String staffEmail) {
        this.staffEmail = staffEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_sex
     *
     * @return the value of staff.staff_sex
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public String getStaffSex() {
        return staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_sex
     *
     * @param staffSex the value for staff.staff_sex
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setStaffSex(String staffSex) {
        this.staffSex = staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.register_date
     *
     * @return the value of staff.register_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.register_date
     *
     * @param registerDate the value for staff.register_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.last_login_date
     *
     * @return the value of staff.last_login_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.last_login_date
     *
     * @param lastLoginDate the value for staff.last_login_date
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
}