package com.hzq.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzq.shop.domain.Cust;
import com.hzq.shop.domain.CustExample;

public interface CustMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int countByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int deleteByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int deleteByPrimaryKey(Long custDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int insert(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int insertSelective(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */List<Cust> selectByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	Cust selectByPrimaryKey(Long custDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */int updateByExampleSelective(@Param("record") Cust record,@Param("example") CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */int updateByExample(@Param("record") Cust record,@Param("example") CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int updateByPrimaryKeySelective(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Sun Oct 16 10:18:33 CST 2016
	 */
	int updateByPrimaryKey(Cust record);
}