package com.hzq.shop.dao;

import com.hzq.shop.domain.CustDetail;
import com.hzq.shop.domain.CustDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int countByExample(CustDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByExample(CustDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByPrimaryKey(Long custDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insert(CustDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insertSelective(CustDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    List<CustDetail> selectByExample(CustDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    CustDetail selectByPrimaryKey(Long custDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") CustDetail record, @Param("example") CustDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExample(@Param("record") CustDetail record, @Param("example") CustDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKeySelective(CustDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_detail
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKey(CustDetail record);
}