package com.hzq.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzq.shop.domain.ProductSort;
import com.hzq.shop.domain.ProductSortExample;

public interface ProductSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int countByExample(ProductSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByExample(ProductSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByPrimaryKey(Long sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insert(ProductSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insertSelective(ProductSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    List<ProductSort> selectByExample(ProductSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    ProductSort selectByPrimaryKey(Long sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductSort record, @Param("example") ProductSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExample(@Param("record") ProductSort record, @Param("example") ProductSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKeySelective(ProductSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sort
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKey(ProductSort record);
}