package com.hzq.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzq.shop.domain.ProductMessg;
import com.hzq.shop.domain.ProductMessgExample;

public interface ProductMessgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int countByExample(ProductMessgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByExample(ProductMessgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByPrimaryKey(Long prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insert(ProductMessg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insertSelective(ProductMessg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    List<ProductMessg> selectByExample(ProductMessgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    ProductMessg selectByPrimaryKey(Long prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductMessg record, @Param("example") ProductMessgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExample(@Param("record") ProductMessg record, @Param("example") ProductMessgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKeySelective(ProductMessg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_messg
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKey(ProductMessg record);
}