package com.hzq.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzq.shop.domain.ProductPhotos;
import com.hzq.shop.domain.ProductPhotosExample;

public interface ProductPhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int countByExample(ProductPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByExample(ProductPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int deleteByPrimaryKey(Long photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insert(ProductPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int insertSelective(ProductPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    List<ProductPhotos> selectByExample(ProductPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    ProductPhotos selectByPrimaryKey(Long photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductPhotos record, @Param("example") ProductPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByExample(@Param("record") ProductPhotos record, @Param("example") ProductPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_photos
     *
     * @mbggenerated Tue Sep 27 23:01:23 CST 2016
     */
    int updateByPrimaryKey(ProductPhotos record);
}