package com.hzq.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzq.shop.domain.Staff;
import com.hzq.shop.domain.StaffExample;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int countByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int deleteByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int deleteByPrimaryKey(Long staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    List<Staff> selectByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    Staff selectByPrimaryKey(Long staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int updateByExample(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Oct 16 10:02:54 CST 2016
     */
    int updateByPrimaryKey(Staff record);
}